spring.application.name=restapp



########### H2
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
#spring.datasource.password=password
spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


##### Logging Configuration #####

# Définir le niveau de log global
logging.level.root=INFO

# Spécifier le fichier de log
logging.file.name=log/trace.log

# Configuration de la politique de rotation des logs (taille max d'un fichier)
logging.logback.rollingpolicy.max-file-size=10MB

# Nombre maximum de fichiers historiques conservés
logging.logback.rollingpolicy.max-history=10
